- name: variables
  hosts: localhost
  connection: local
  vars:
    URL: play.google.com.au
  tasks:
    - name: Print a variable
      vars:
        URL: task.google.com.au
      ansible.builtin.debug:
        msg: Var URL - {{ URL }}

    - name: Print a variable
      ansible.builtin.debug:
       msg: Var URL - {{ URL }}
       msg1: "{{ URL }}"

    ## KEY: "{{ VAR }}" Ansible expects double quotes

