- name: Playbook [localhost] System Variables
  hosts: localhost
  connection: local
  vars:
    URL: play.google.com
  vars_files:
    - just-vars.yml
  tasks:
    - name: Print fact
      ansible.builtin.debug:
        msg: "{{ ansible_architecture }}"