- name: variables
  hosts: localhost
  connection: local
  vars:
    URL: play.google.com

  tasks:
    - name: Print First Task Variable
      vars:
        URL: task.google.com
        ansible.builtin.debug:
          msg: Var URL - {{URL}}

    - name: Print Second Task Variable
      ansible.builtin.debug:
      msg: Var URL - {{URL}}
