- name: Variables
  hosts: localhost
  connection: local
  vars:
    URL: play.google.com
  vars_files:
    - just-vars.yml

  tasks:
    - name: Task-1 ls command output moving to out variable
      ansible.builtin.shell: ls
      register: out

    - name: Printing ls command output from out variable
      ansible.builtin.debug:
        msg: "{{ out }}"