- name: Playbook - Ansible Filters
  hosts: localhost
  connection: local
  vars:
    URL: https://dlcdn.apache.org/tomcat/apache-tomcat-11.0.2.zip
  tasks:
    - name: Task1 - Filters Full
      ansible.builtin.debug:
        msg: "{{ URL | split('/') }}"

    - name: Task2 - Filters First Word
      ansible.builtin.debug:
        msg: "{{ URL | split('/') | first}}"

    - name: Task3 - Filters Last Word
      ansible.builtin.debug:
       msg: "{{ URL | split('/') | last}}"
