- name: Playbook - Ansible Error Handling
  hosts: localhost
  connection: local
  vars:
    URL: google.com
  tasks:
    - name: Task - Print
      ansible.builtin.shell: cat /etc/passwd | grep DEMO
      ignore_errors: true

    - name: Task - List
      ansible.builtin.shell: ls
      register: URL

    - name: Task - Print
      ansible.builtin.debug:
       msg: command output - {{ URL }}