- name: Playbook - Ansible Error Handling
  hosts: localhost
  connection: local
  tasks:
    - name: Task - Print
      ansible.builtin.shell: cat /etc/passwd | grep DEMO
      ignore_errors: true

    - name: Task - List
      ansible.builtin.shell: ls
      register: out

    - name: Task - Print ls Output
      ansible.builtin.debug:
      msg: ls command output - {{ out }}