- name: Playbook - Ansible Only Copy
  hosts: localhost
  connection: local

  tasks:
    - name: Task - Copy Collection
      ansible.builtin.copy:
        src: test.txt
        dest: /tmp/test-copy.txt

    - name: Task - template collection
      ansible.builtin.template:
        src: test.txt
        dest: /tmp/test1-copy.txt

### Execute command as, $ansible-playbook 09-template1.yml