- name: Playbook - Ansible Copy and Replace Template
  hosts: localhost
  connection: local

  tasks:
    #     - name: Copy a file
    #       ansible.builtin.copy:
    #         src: test.txt
    #         dest: /tmp/test-copy.txt

    - name: Task - Copy and Replace
      ansible.builtin.template:
        src: test.txt
        dest: /tmp/test-copy.txt

### Execute command as, $ansible-playbook -e name=John