- name: Playbook - Ansible Template
  hosts: localhost
  connection: local

  tasks:
    #     - name: Copy a file
    #       ansible.builtin.copy:
    #         src: test.txt
    #         dest: /tmp/test-copy.txt

    - name: Task - Copy Collection
      ansible.builtin.template:
        src: test.txt
        dest: /tmp/test-copy.txt