- name: Playbook - Ansible Only Copy
  hosts: localhost
  connection: local

  tasks:
         - name: Task Only Copy
           ansible.builtin.copy:
             src: test.txt
             dest: /tmp/test1-copy.txt

#    - name: Task - Only Copy
#      ansible.builtin.template:
#        src: test.txt
#        dest: /tmp/test1-copy.txt

### Execute command as, $ansible-playbook 09-template1.yml